version: '3'

vars:
  OREILLY_DIR: browser
  SPEC_FILE: openapi.yaml
  OUTPUT_DIR: generated/api
  CONFIG_FILE: oapi-codegen.yaml
  BINARY_NAME: orm-discovery-mcp-go
  BIN_DIR: ./bin

tasks:
  # === Code Generation ===
  generate:api:oreilly:
    desc: OpenAPI仕様からO'Reilly Learning Platformのクライアントコードを生成
    dir: '{{.OREILLY_DIR}}'
    sources:
      - '{{.SPEC_FILE}}'
      - '{{.CONFIG_FILE}}'
    generates:
      - '{{.OUTPUT_DIR}}/client.gen.go'
    cmds:
      - rm -rf {{.OUTPUT_DIR}}
      - mkdir -p {{.OUTPUT_DIR}}
      - oapi-codegen --config={{.CONFIG_FILE}} {{.SPEC_FILE}}

  # === Code Quality ===
  format:
    desc: Goコードのフォーマットを実行
    deps: [generate:api:oreilly]
    sources:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    cmds:
      - go mod tidy
      - goimports -l -w .
      - go fmt ./...

  lint:
    desc: Goコードのリントを実行
    deps: [format]
    sources:
      - '**/*.go'
      - '.golangci.yml'
    cmds:
      - golangci-lint run --timeout=5m

  # === Testing ===
  test:
    desc: Goのテストを実行
    deps: [generate:api:oreilly]
    sources:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    cmds:
      - go test ./... -v

  test:unit:
    desc: Unitテストのみを実行（E2Eを除く）
    deps: [generate:api:oreilly]
    sources:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    cmds:
      - go test $(go list ./... | grep -v /e2e) -v -short

  test:e2e:
    desc: E2Eテストを実行（認証情報必須、race検査付き）
    deps: [lint]
    sources:
      - '**/*_e2e_test.go'
      - '**/*_test.go'
      - 'go.mod'
      - 'go.sum'
    cmds:
      - go test ./... -tags=e2e -v -race

  test:coverage:
    desc: カバレッジ付きでテストを実行
    deps: [generate:api:oreilly]
    sources:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    generates:
      - 'coverage.out'
    cmds:
      - go test ./... -v -race -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html

  # === Building ===
  build:
    desc: Goのビルドを実行
    deps: [generate:api:oreilly, lint]
    sources:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    generates:
      - '{{.BIN_DIR}}/{{.BINARY_NAME}}'
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -trimpath -o {{.BIN_DIR}}/{{.BINARY_NAME}} .

  build:release:
    desc: リリース用ビルド（最適化あり）
    deps: [generate:api:oreilly, lint, test]
    sources:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
    generates:
      - '{{.BIN_DIR}}/{{.BINARY_NAME}}'
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - |
        go build -trimpath \
          -ldflags="-s -w -X main.version=dev -X main.commit=local -X main.date={{now | date \"2006-01-02T15:04:05Z07:00\"}}" \
          -o {{.BIN_DIR}}/{{.BINARY_NAME}} .

  install:
    desc: Go バイナリをGOPATH/binにインストール（常にクリーンビルド）
    deps: [generate:api:oreilly, lint]
    vars:
      GIT_VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
      GIT_COMMIT:
        sh: git rev-parse --short HEAD 2>/dev/null || echo "none"
      BUILD_DATE:
        sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
    cmds:
      - go clean -i .
      - |
        go install -trimpath -v \
          -ldflags="-X main.version={{.GIT_VERSION}} -X main.commit={{.GIT_COMMIT}} -X main.date={{.BUILD_DATE}}" \
          .

  # === Cleaning ===
  clean:generated:
    desc: 生成されたコードを削除
    dir: '{{.OREILLY_DIR}}'
    cmds:
      - rm -rf {{.OUTPUT_DIR}}/*.gen.go

  clean:build:
    desc: ビルド成果物を削除
    cmds:
      - rm -rf {{.BIN_DIR}}

  clean:test:
    desc: テスト成果物を削除
    cmds:
      - rm -f coverage.out coverage.html

  clean:all:
    desc: すべての生成ファイルを削除
    deps: [clean:generated, clean:build, clean:test]

  # === Plugin Validation ===
  plugin:validate:marketplace:
    desc: マーケットプレイスとプラグイン設定の統合検証
    sources:
      - '.claude-plugin/**/*'
      - 'plugins/agents/**/*.md'
    cmds:
      - claude plugin validate .
      - |
        echo "=== JSON形式検証 ==="
        cat .claude-plugin/marketplace.json | python3 -m json.tool > /dev/null && echo "✓ marketplace.json は有効なJSON形式です"
        cat .claude-plugin/plugin.json | python3 -m json.tool > /dev/null && echo "✓ plugin.json は有効なJSON形式です"

        echo ""
        echo "=== 必須フィールド検証 ==="
        if grep -q '"name"' .claude-plugin/marketplace.json && \
           grep -q '"owner"' .claude-plugin/marketplace.json && \
           grep -q '"plugins"' .claude-plugin/marketplace.json; then
          echo "✓ marketplace.json: 必須フィールドが存在します"
        else
          echo "✗ marketplace.json: 必須フィールドが不足しています (name, owner, plugins)"
          exit 1
        fi

        echo ""
        echo "=== バージョン同期検証 ==="
        MARKETPLACE_VER=$(python3 -c "import json; print(json.load(open('.claude-plugin/marketplace.json'))['metadata']['version'])")
        PLUGIN_VER=$(python3 -c "import json; print(json.load(open('.claude-plugin/plugin.json'))['version'])")
        PLUGINS_VER=$(python3 -c "import json; print(json.load(open('.claude-plugin/marketplace.json'))['plugins'][0]['version'])")
        if [ "$MARKETPLACE_VER" = "$PLUGIN_VER" ] && [ "$MARKETPLACE_VER" = "$PLUGINS_VER" ]; then
          echo "✓ バージョンが同期しています: $MARKETPLACE_VER"
        else
          echo "✗ バージョン不一致: metadata=$MARKETPLACE_VER, plugin.json=$PLUGIN_VER, plugins[]=$PLUGINS_VER"
          exit 1
        fi

        echo ""
        echo "=== エージェント定義検証 ==="
        for agent in $(python3 -c "import json; agents=json.load(open('.claude-plugin/plugin.json')).get('agents',[]); [print(a) for a in agents]"); do
          if [ ! -f "$agent" ]; then
            echo "✗ エージェントファイルが見つかりません: $agent"
            exit 1
          fi
          if head -1 "$agent" | grep -q "^---"; then
            echo "✓ エージェント Frontmatter 存在: $agent"
          else
            echo "✗ エージェント Frontmatter が不足: $agent"
            exit 1
          fi
        done

        echo ""
        echo "=== MCP サーバー設定検証 ==="
        if python3 -c "import json; servers=json.load(open('.claude-plugin/plugin.json')).get('mcpServers',{}); exit(0 if servers else 1)" 2>/dev/null; then
          echo "⚠ MCP サーバーが設定されています。バイナリが PATH 上にあることを確認してください"
          python3 -c "import json; servers=json.load(open('.claude-plugin/plugin.json')).get('mcpServers',{}); [print(f'  - {k}: {v.get(\"command\",\"\")}') for k,v in servers.items()]"
        fi

        echo ""
        echo "=== セキュリティ検証 ==="
        if grep -rE "(password|secret|api_key)\s*[=:]\s*['\"][^$]" .claude-plugin/ 2>/dev/null | grep -v '\${'; then
          echo "✗ ハードコードされた認証情報が検出されました"
          exit 1
        else
          echo "✓ ハードコードされた認証情報はありません"
        fi

        echo ""
        echo "✓ マーケットプレイス検証が完了しました"

  # === Composite Tasks ===
  dev:
    desc: 開発用タスク（フォーマット + リント + テスト）
    deps: [format, lint, test]

  ci:
    desc: CI用タスク（すべてのチェック + ビルド + プラグイン検証）
    deps: [format, lint, test:coverage, build, plugin:validate:marketplace]

  all:
    desc: すべてのタスクを実行
    deps: [ci]

  # === Utilities ===
  deps:
    desc: Go依存関係の更新
    cmds:
      - go mod tidy
      - go mod download

  check:
    desc: コードの基本チェック
    deps: [format, lint]
